services:
  postgres:
    image: postgres:17

    container_name: spendly-postgres

    restart: unless-stopped

    environment:
      POSTGRES_USER: spendly
      POSTGRES_PASSWORD: spendly
      POSTGRES_DB: spendly

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: